name: Code sniffer
on: [pull_request]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: Code sniffer
    steps:
      - name: Install php dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.2'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Save Token
        # Step should be removed when PHP-SDK is released
        run: composer config --global github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}
      - name: Install dependencies
        run: composer install
      - name: Run Code sniffer
        run: composer code-sniffer
